project_name: SmartHome.Hub

builds:
  - binary: SmartHome.Hub
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - formats: [tar.gz]

checksum:
  name_template: checksums.txt
  
release:
  github:
    owner: madirajupranaykashyap
    name: SmartHome.Hub